### ISSUE TITLE
C++ easy coding via GDNative technology

### ISSUE THREAD

**Issue by amirea** [godotengine/godot-headers#14]
If you accept suggestions, I have one that would be very welcomed by C++ users (me included), judging by feedback on the internet. Additionally, the idea may be applied to other languages as well.
Although coding in C++ is doable as it currently is, it's always better (for the users) to be able to simplify it and bring it as close to GDScript-ing as possible. So, do you think it would be feasible to automate most part of the workload more or less like:

- let the users write cpp's for individual nodes, with the respective callbacks like _ready(), _process(), etc.
- automatically wrap the cpp's and h's with code necessary for registering the classes and methods (maybe based on access modifiers - only register `public` ones).
- build whole code into an so/dll.
- in Godot make a new Language like "external C++" that when created, it automatically creates behind the gdnlib and gdns (or maybe combine them into a dedicated type according to the language, C++, D, etc.
- when pressed, the script button next to the node would bring up the IDE.

The advantage: the user only worries about the actual cpp/h and when s/he modifies the code in the IDE, all the "re-importing" process (re-building, overwriting the so/dll) happens automatically.

Disadvantage: the user wouldn't have the same degree of freedom but then again, they'd be spared from the workload and it would be more than perfect for those looking for a simple way to code in C++ (like in Unreal). This would probably not work great with 3rd party libraries but it's great for C++ node scripting.

**Comment by karroffel** [comment]
Thank you for your suggestion!

Such an external C++ language could already be possible by using PluginScript for wrapping NativeScript while providing more editor integrations.

For the more scripting like features in C++ itself a different build setup is needed that would need to parse the source files, much like Qt and also Unreal do it. While I like those things from a usability standpoint it makes the process less transparent (which is fine for some users but not for other).

So in order to have such a thing a compiler library suite (like libclang for python or so) would be needed to get the data and then generate the needed code.

If someone wants to work on that - feel free! I would just like if that would be kept *optional* so that users who just want to use some bindings for convenience can just do that and don't need to trust a pre-compiler to generate the correct code.

**Comment by Calinou** [comment]
There's now a [Godot proposal](https://github.com/godotengine/godot-proposals/issues/119) covering this, so I think this issue can be closed.
